<?php

declare(strict_types = 1);

namespace Fluix\Config\Dump;

use Fluix\Config\Dumper;
use Fluix\Config\File;

final class PhpConstDumper implements Dumper
{
    public function dump(File $file, array $config): void
    {
        ob_start();
        echo "<" . "?php\n";
        echo "// generated by " . static::class . ", do not edit\n";
        foreach ($config as $k => $v) {
            echo "define('{$k}', " . var_export($v, true) . ");\n";
        }
        $file->write(ob_get_clean());
    }
}
