<?php

declare(strict_types = 1);

namespace Fluix\Config\Dump;

use Fluix\Config\Dumper;

class PhpConstDumperTest extends AbstractDumperTest
{
    public function supportProvider(): array
    {
        return [
            ["const", true],
            ["json", false],
            ["php", false],
        ];
    }
    
    public function dumpProvider(): array
    {
        $expected = <<<CONTENT
<?php
// generated by Fluix\Config\Dump\PhpConstDumper, do not edit
define('qwe', 1);
CONTENT;
        
        return [
            [["qwe" => 1], $expected],
        ];
    }
    
    protected function basename(): string
    {
        return "config.php";
    }
    
    protected function dumper(): Dumper
    {
        return new PhpConstDumper();
    }
}
