<?php

declare(strict_types = 1);

namespace Fluix\Config\Dump;

use Fluix\Config\Dumper;

class PhpDumperTest extends AbstractDumperTest
{
    public function dumpProvider(): array
    {
        $expected = <<<CONTENT
<?php
// generated by Fluix\Config\Dump\PhpDumper, do not edit
return array (
  'int' => 1,
  'string' => 'string',
  'boolean' => false,
  'array' =>
  array (
    0 => 1,
    1 => '2',
    2 => 3,
  ),
);
CONTENT;
        
        return [
            [
                ["int" => 1, "string" => "string", "boolean" => false, "array" => [1,"2",3]],
                $expected,
            ],
        ];
    }
    
    protected function format(): Format
    {
        return Format::php();
    }
    
    protected function dumper(): Dumper
    {
        return new PhpDumper();
    }
}
