<?php

declare(strict_types = 1);

namespace Fluix\Config\Dump;

use Fluix\Config\Dumper;
use Fluix\Config\File;

final class PhpDumper implements Dumper
{
    public function dump(File $file, array $values): void
    {
        ob_start();
        echo "<" . "?php\n";
        echo "// generated by " . static::class . ", do not edit\n";
        echo "return " . var_export($values, true) . ";";
        $file->write(ob_get_clean());
    }
    
    public function supports(Format $format): bool
    {
        return $format->equals(Format::php());
    }
}
